name: Test Argo Job

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Versions
        run: |
          echo "Kubectl: $(kubectl version)"
          echo "Helm: $(helm version)"
          echo "Kind: $(kind version)"
      - name: Create Cluster
        run: kind create cluster
      - name: Kube Status
        run: |
          echo "Kubectl Context:" $(kubectl config current-context)
          echo "Kube Config: ${KUBECONFIG}"
          echo "Cluster Info:"
          kubectl cluster-info
          echo "Pods:"
          kubectl get pods -n kube-system
